### PR TITLE
Add shebang line

### PR DESCRIPTION
**Pull request by deldesir**
This restores the shebang line

### CODE REVIEW

**Comment by holta** [comment]
Building on:

- PR #1

**Comment by holta** [comment]
> This restores the shebang line

@deldesir is this PR smoke-tested and/or functionality-tested?

Thanks much for clarifying, both here and in general!

**Comment by deldesir** [comment]
@holta, this was functionality-tested on Ubuntu 22.04 by generating two ZIM files. As expected, log files were generated for each run. No effect on the output though, since the constants.py file was not executed like a standalone executable or double clicked in a file manager. Thanks anyway for the reminder.

**Comment by holta** [comment]
> @holta, this was functionality-tested on Ubuntu 22.04 by generating two ZIM files

@georgejhunt can you merge this?

@deldesir are other logging improvements forthcoming in coming days?  (Or is this good enough!)

PS Can someone pastebin an example `/output/run.log` log file to illustrate please if possible?

**Comment by holta** [comment]
Context for others:

- https://github.com/georgejhunt/youtube/wiki/cookbook.md
- https://github.com/georgejhunt/youtube/wiki/zimbabwe_footprint.md

**Pull request merged**
