### PR TITLE
Replace titles of all videos in a youtube playlist 

### PR DESCRIPTION
**Pull request by deldesir**
Works as intended. This replaces youtube titles and add them in two JSON files used by youtube2zim.
This was smoke-tested on Ubuntu 22.10.

### CODE REVIEW

**Comment by holta** [comment]
@deldesir can you consider a more descriptive title for this PR &mdash; to help others understand?

Maybe something like "WIP: json replacer to customize video titles" ?

**Comment by deldesir** [comment]
@holta, this solves the specific problem of titles that someone would want to change. Although it is subject to improvement in the future, it can be merged because it serves its purpose.

**Comment by holta** [comment]
CSV files appear inherently dangerous (commas are a normal part of human-readable text).

1) So this PR should probably not be merged, until that assumption is reworked &mdash; likely with .json input instead?
2) If so, we should provide instructions for cleanly converting Excel / Google Sheets (spreadsheet) to the appropriate .json &mdash; i.e. a clean one-to-one mapping from each YouTube's 11-character ID to the actual/concise video title students should see.

**Comment by holta** [comment]
FYI the current proposal is to fix the CSV problems of this PR with a [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) focus on text files, so that this gets done quickly, in keeping with the UNIX tradition of [storing data in flat text files for simplicity](https://en.wikipedia.org/wiki/Unix_philosophy#Mike_Gancarz:_The_UNIX_Philosophy):

```
--custom-titles <youtube-video-ids.txt> <custom-video-titles.txt>
```

That's 2 input files:

1. Input text file **<youtube-video-ids.txt>** should be a single column (i.e. separated by newlines) containing the 11-character YouTube ID's for every video that needs its title customized in the output ZIM file.
2. Input text file **<custom-video-titles.txt>** should be a single column (i.e. separated by newlines) containing the custom video titles, i.e. for each video listed in <youtube-video-ids.txt> (in that same order).

CLARIFS:

- Operator who provide faulty input should be shown clear error messages, telling them exactly what's wrong and why.  Hypothetical Examples:
  - ERROR: Video Title Missing (from custom-video-titles.txt) for YouTube Video ID [actual 11-character ID] in youtube-video-ids.txt
  - ERROR: YouTube Video ID [actual 11-character ID] (from youtube-video-ids.txt) does not exist in YouTube Playlist [actual 18-character ID].
  - ERROR: YouTube Video ID [actual 11-character ID] appears more than once in youtube-video-ids.txt
  - ERROR: Duplicate video titles are not allowed ("[actual video title]" appears associated with multiple videos: [actual 11-character ID], [actual 11-character ID] ETC).  _Perhaps validate at the very end, after all playlist video titles have been customized?!_
- If absolutely necessary, a more intricate/fragile JSON strategy can be developed in future.

**Comment by deldesir** [comment]
> FYI the current proposal is to fix the CSV problems of this PR with a [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) focus on text files, so that this gets done quickly, in keeping with the UNIX tradition of [storing data in flat text files for simplicity](https://en.wikipedia.org/wiki/Unix_philosophy#Mike_Gancarz:_The_UNIX_Philosophy):
> 
> ```
> --custom-titles <youtube-video-ids.txt> <custom-video-titles.txt>
> ```
> 
> That's 2 input files:
> 
>     1. Input text file **<youtube-video-ids.txt>** should be a single column (i.e. separated by newlines) containing the 11-character YouTube ID's for every video that needs its title customized in the output ZIM file.
> 
>     2. Input text file **<custom-video-titles.txt>** should be a single column (i.e. separated by newlines) containing the custom video titles, i.e. for each video listed in <youtube-video-ids.txt> (in that same order).
> 
> 
> CLARIFS:
> 
>     * Operator who provide faulty input should be shown clear error messages, telling them exactly what's wrong and why.  Hypothetical Examples:
>       
>       * ERROR: Video Title Missing (from custom-video-titles.txt) for YouTube Video ID [actual 11-character ID] in youtube-video-ids.txt
>       * ERROR: YouTube Video ID [actual 11-character ID] (from youtube-video-ids.txt) does not exist in YouTube Playlist [actual 18-character ID].
>       * ERROR: YouTube Video ID [actual 11-character ID] appears more than once in youtube-video-ids.txt
>       * ERROR: Duplicate video titles are not allowed ("[actual video title]" appears associated with multiple videos: [actual 11-character ID], [actual 11-character ID] ETC).  _Perhaps validate at the very end, after all playlist video titles have been customized?!_
> 
This is implemented and tested on ubuntu 22.10. It takes into account two files independently of their names, provided that one contains YouTube links and the other titles.

UPDATE: Work in progress

**Comment by deldesir** [comment]
UPDATE: I tested this extensively and come to the point this is finally ready to be merged even though  changes are likely to come based of eventual improvement over time.

**Comment by holta** [comment]
"Files changed 43" makes it very hard for others to understand this PR:
https://github.com/georgejhunt/youtube/pull/4/files

(If possible rebase or similar, to make the changes clearly legible?)

**Comment by holta** [comment]
FYI a new doc is tracking this PR's ongoing progress:

https://github.com/georgejhunt/youtube/wiki/Cookbook2

This should be made clear at the top of the older doc:

https://github.com/georgejhunt/youtube/wiki/cookbook.md

**Comment by deldesir** [comment]
Deviated from the initial objective

**Comment by holta** [comment]
> Deviated from the initial objective

Open individual/new PR(s) to accomplish each objective?

**Pull request closed without merging**
